[context.production]
  publish = "dist/"
  command = "pnpm build"
  environment = { NODE_VERSION = "16.19.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404